# Generated by Django 3.1.2 on 2021-01-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRKSatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrksatunoinden', models.CharField(blank=True, max_length=50, null=True)),
                ('mrksatugred', models.CharField(blank=True, max_length=20, null=True)),
                ('mrksatukategori', models.CharField(blank=True, max_length=20, null=True)),
                ('mrksatupengkhususan', models.CharField(blank=True, max_length=100, null=True)),
                ('mrksatutarikhmula', models.CharField(blank=True, max_length=50, null=True)),
                ('mrksatutarikhjangkasiap', models.CharField(blank=True, max_length=50, null=True)),
                ('mrksatukosprojek', models.CharField(blank=True, max_length=100, null=True)),
                ('mrksatutarikhdaftar', models.CharField(blank=True, max_length=50, null=True)),
                ('mrksatunosebutharga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.noperolehan')),
            ],
        ),
        migrations.RenameModel(
            old_name='MRK2',
            new_name='MRKDua',
        ),
        migrations.DeleteModel(
            name='MRK1',
        ),
    ]
