# Generated by Django 3.2 on 2021-07-07 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kosprojek',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
        migrations.AlterField(
            model_name='laporansiapkerja',
            name='lskmrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bindtwo', to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='laporansiapkerja',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='mrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bindone', to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
        migrations.AlterField(
            model_name='mrksatu',
            name='mrksatukontraktor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.kontraktor'),
        ),
        migrations.AlterField(
            model_name='mrksatu',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
        migrations.AlterField(
            model_name='mrktiga',
            name='marktigamrksatu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='mrktiga',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
        migrations.AlterField(
            model_name='perakuanpwjp',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
        migrations.AlterField(
            model_name='perakuanpwjp',
            name='wjpmrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='psk',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
        migrations.AlterField(
            model_name='psk',
            name='pskmrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='psmk',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
        migrations.AlterField(
            model_name='psmk',
            name='psmkmrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='senaraisemakan',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
        migrations.AlterField(
            model_name='senaraisemakan',
            name='ssmrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='suratkhas',
            name='khasmrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='suratkhas',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
        migrations.AlterField(
            model_name='suratmrk',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
        migrations.AlterField(
            model_name='suratmrk',
            name='smrkmrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='suratpelepasanbon',
            name='bonmrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='suratpelepasanbon',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
        migrations.AlterField(
            model_name='suratpjaminanbank',
            name='jbankmrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='suratpjaminanbank',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jpskit.projek'),
        ),
    ]
