# Generated by Django 3.2 on 2021-07-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdvot',
            name='tahun',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
