# Generated by Django 3.1.2 on 2020-10-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontraktor',
            name='konImage',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
