# Generated by Django 3.1.2 on 2021-01-15 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jpskit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noperolehan',
            name='pegawaiselia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
