# Generated by Django 3.1.2 on 2020-10-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontraktor',
            name='konDaerah',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
