# Generated by Django 3.2 on 2021-04-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistem',
            name='sistemname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subsistem',
            name='subsistemname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='komponen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subidlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpskit.subsistem')),
            ],
        ),
    ]
