# Generated by Django 3.2 on 2021-08-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='kategori',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
