# Generated by Django 3.2 on 2021-04-22 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jpskit', '0002_auto_20210419_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_startdate', models.CharField(blank=True, max_length=12, null=True)),
                ('course_endate', models.CharField(blank=True, max_length=12, null=True)),
                ('course_place', models.CharField(blank=True, max_length=12, null=True)),
                ('course_year', models.CharField(blank=True, max_length=8, null=True)),
                ('course_days', models.CharField(blank=True, max_length=20, null=True)),
                ('course_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sokongan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sokonganname', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitname', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attandance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayone', models.CharField(blank=True, max_length=5, null=True)),
                ('daytwo', models.CharField(blank=True, max_length=5, null=True)),
                ('daythree', models.CharField(blank=True, max_length=5, null=True)),
                ('dayfour', models.CharField(blank=True, max_length=5, null=True)),
                ('dayfive', models.CharField(blank=True, max_length=5, null=True)),
                ('daysix', models.CharField(blank=True, max_length=5, null=True)),
                ('dayseven', models.CharField(blank=True, max_length=5, null=True)),
                ('dayeight', models.CharField(blank=True, max_length=5, null=True)),
                ('daynine', models.CharField(blank=True, max_length=5, null=True)),
                ('dayten', models.CharField(blank=True, max_length=5, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpskit.course')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
