# Generated by Django 3.1.2 on 2021-01-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0002_auto_20210129_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrksatu',
            name='mrksatukontraktor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.kontraktor'),
        ),
    ]
