# Generated by Django 3.2 on 2021-07-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0002_auto_20210707_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sokongan',
        ),
        migrations.DeleteModel(
            name='UnitGroup',
        ),
        migrations.AddField(
            model_name='attandance',
            name='eight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attandance',
            name='five',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attandance',
            name='four',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attandance',
            name='one',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attandance',
            name='projekbind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.course'),
        ),
        migrations.AddField(
            model_name='attandance',
            name='seven',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attandance',
            name='six',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attandance',
            name='three',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attandance',
            name='two',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hari',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tahun',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tajukkursus',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tarikhakhir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tarikhmula',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tempat',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='batchno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gambar',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groupunit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nokp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unitsokongan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
