# Generated by Django 3.2 on 2021-07-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0003_auto_20210708_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tajukkursus',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
