# Generated by Django 3.2 on 2021-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0003_alter_mrksatu_mrksatutarikhdaftar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrkdua',
            name='mrkduaLADSehingga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='mrkduaLADdari',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='mrkduakerjasebenartarikh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='mrkdualanjutdari',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='mrkdualanjutsehingga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='mrkduamansuh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='mrkduaperakuan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='mrkduatarikhlaporan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrksatu',
            name='mrksatutarikhdaftar',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrksatu',
            name='mrksatutarikhmula',
            field=models.DateField(blank=True, null=True),
        ),
    ]
