# Generated by Django 3.1.2 on 2021-01-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0003_mrksatu_mrksatukontraktor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRKKursus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kscode', models.CharField(blank=True, max_length=50, null=True)),
                ('ksname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
