# Generated by Django 3.2 on 2021-04-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0003_auto_20210423_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projek',
            name='tajukkerja',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
