# Generated by Django 3.1.2 on 2020-10-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontraktor',
            name='konImage',
        ),
    ]
