# Generated by Django 3.1.2 on 2021-01-15 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jpskit', '0004_auto_20210116_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noperolehan',
            name='pegawaiselia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
