# Generated by Django 3.2 on 2021-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0004_alter_projek_tajukkerja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrkdua',
            name='mrkdualanjutdari',
        ),
        migrations.AlterField(
            model_name='laporansiapkerja',
            name='lsklaporan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='mrkduadisebabkan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='mrkduadisebabkanoleh',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='mrkdualainlain',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
