# Generated by Django 3.2 on 2021-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0005_auto_20210612_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrktiga',
            name='mrktigatarikh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
