# Generated by Django 3.1.2 on 2020-10-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0005_auto_20201025_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontraktor',
            name='konImage',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
