# Generated by Django 3.2 on 2021-04-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0005_auto_20210427_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrkdua',
            name='mrkdualanjutdari',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
