# Generated by Django 3.1.2 on 2021-01-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0005_auto_20210129_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporansiapkerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='issungai',
            options={'verbose_name_plural': 'Sungai'},
        ),
        migrations.AlterModelOptions(
            name='mrkdua',
            options={'verbose_name_plural': 'MRK 2'},
        ),
        migrations.AlterModelOptions(
            name='mrksatu',
            options={'verbose_name_plural': 'MRK 1'},
        ),
        migrations.AddField(
            model_name='mrkdua',
            name='mrkduadisebabkanoleh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
