# Generated by Django 3.1.2 on 2021-01-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0006_auto_20210129_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laporansiapkerja',
            options={'verbose_name_plural': 'Laporan Siap Kerja'},
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskhargasebenar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskjawatanj41',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskjawatanjuruteradaerah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskjawatanketuabahagian',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskjenisinsurancedua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskjenisinsurancesatu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskjuruteradaerah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskjuruteraj41',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskkerjasiap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskketuabahagian',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lsklanjutmasa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lsklaporan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskmrksatulink',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lsknoinsurancedua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lsknoinsurancesatu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lsknosebutharga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskperkeso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lskperuntukan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporansiapkerja',
            name='lsktarikhperakui',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
