# Generated by Django 3.2 on 2021-04-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0006_mrkdua_mrkdualanjutdari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrktiga',
            name='mrktigasokongan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
