# Generated by Django 3.1.2 on 2020-10-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0006_kontraktor_konimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontraktor',
            name='konImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
