# Generated by Django 3.2 on 2021-06-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0006_alter_mrktiga_mrktigatarikh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psk',
            name='psktarikhambilmilik',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psk',
            name='psktarikhmulatanggug',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psk',
            name='psktarikhtamattanggung',
            field=models.DateField(blank=True, null=True),
        ),
    ]
