# Generated by Django 3.2 on 2021-05-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0007_alter_mrktiga_mrktigasokongan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psk',
            name='psktarikhsiapsebenar',
        ),
    ]
