# Generated by Django 3.1.2 on 2021-01-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0007_auto_20210129_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRKTiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
