# Generated by Django 3.2 on 2021-06-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0007_auto_20210612_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senaraisemakan',
            name='sstarikh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
