# Generated by Django 3.1.2 on 2020-10-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0007_auto_20201025_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_sebutharga', models.CharField(blank=True, max_length=150, null=True)),
                ('o_tarikh', models.CharField(blank=True, max_length=50, null=True)),
                ('o_permilik', models.CharField(blank=True, max_length=150, null=True)),
                ('o_jenis', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
