# Generated by Django 3.2 on 2021-06-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0008_alter_senaraisemakan_sstarikh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratmrk',
            name='smrktarikh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
