# Generated by Django 3.1.2 on 2021-01-29 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0008_mrktiga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mrktiga',
            options={'verbose_name_plural': 'MRK 3'},
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='marktigamrksatu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.mrksatu'),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mkrtigamutukerangka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrkcatat1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrkcatat2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrkcatat3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrkcatat4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrkcatat5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrkcatat6',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrkcatat7',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrkcatat8',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrktigabina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrktigakemajuan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrktigamutukemasan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrktigamutukerja',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrktigamutukerjaluar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrktigapegawasan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrktigasebutharga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.noperolehan'),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrktigasokongan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrktigatadbir',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrktiga',
            name='mrktigatarikh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
