# Generated by Django 3.2 on 2021-05-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0008_remove_psk_psktarikhsiapsebenar'),
    ]

    operations = [
        migrations.AddField(
            model_name='senaraisemakan',
            name='sstarikh',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
