# Generated by Django 3.2 on 2021-05-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0009_senaraisemakan_sstarikh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratpelepasanbon',
            name='bonalamatdua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='suratpelepasanbon',
            name='bonalamatsatu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='suratpelepasanbon',
            name='bonkepada',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='suratpelepasanbon',
            name='bonmelalui',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
