# Generated by Django 3.1.2 on 2021-01-29 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0009_auto_20210130_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporansiapkerja',
            name='lskmrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='laporansiapkerja',
            name='lsknosebutharga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.noperolehan'),
        ),
    ]
