# Generated by Django 3.2 on 2021-06-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0009_alter_suratmrk_smrktarikh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noperolehan',
            name='tarikh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
