# Generated by Django 3.1.2 on 2021-01-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0010_auto_20210116_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projek',
            old_name='nosebuthargalink',
            new_name='nosebuthargaid',
        ),
        migrations.RemoveField(
            model_name='projek',
            name='pegawaiselia',
        ),
    ]
