# Generated by Django 3.2 on 2021-06-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0010_alter_noperolehan_tarikh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kosprojek',
            name='kos_mrksatulink',
        ),
    ]
