# Generated by Django 3.2 on 2021-05-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0010_auto_20210515_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratpelepasanbon',
            name='bonwanjaminan',
        ),
        migrations.AddField(
            model_name='suratpelepasanbon',
            name='bonwangjaminan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
