# Generated by Django 3.1.2 on 2021-02-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0010_auto_20210130_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psktarikhsiapsebenar', models.CharField(blank=True, max_length=50, null=True)),
                ('psktarikhambilmilik', models.CharField(blank=True, max_length=50, null=True)),
                ('psktarikhmulatanggug', models.CharField(blank=True, max_length=50, null=True)),
                ('psktarikhtamattanggung', models.CharField(blank=True, max_length=50, null=True)),
                ('pskmrksatulink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.mrksatu')),
                ('psknosebutharga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.noperolehan')),
            ],
            options={
                'verbose_name_plural': 'Perakuan Siap Kerja',
            },
        ),
    ]
