# Generated by Django 3.2 on 2021-06-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0011_remove_kosprojek_kos_mrksatulink'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosprojek',
            name='kosnosebut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.noperolehan'),
        ),
    ]
