# Generated by Django 3.1.2 on 2020-12-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0011_auto_20201229_0601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LSK',
        ),
        migrations.DeleteModel(
            name='MR1',
        ),
        migrations.DeleteModel(
            name='MR2',
        ),
        migrations.DeleteModel(
            name='MR3',
        ),
        migrations.DeleteModel(
            name='PSK',
        ),
        migrations.DeleteModel(
            name='SS',
        ),
    ]
