# Generated by Django 3.1.2 on 2021-02-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0011_psk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenaraiSemakan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssinden', models.CharField(blank=True, max_length=10, null=True)),
                ('sslsk', models.CharField(blank=True, max_length=10, null=True)),
                ('ssti', models.CharField(blank=True, max_length=10, null=True)),
                ('sssebutharga', models.CharField(blank=True, max_length=10, null=True)),
                ('sspt', models.CharField(blank=True, max_length=10, null=True)),
                ('ssjs', models.CharField(blank=True, max_length=10, null=True)),
                ('sskts', models.CharField(blank=True, max_length=10, null=True)),
                ('ssds', models.CharField(blank=True, max_length=10, null=True)),
                ('ssplm', models.CharField(blank=True, max_length=10, null=True)),
                ('ssab', models.CharField(blank=True, max_length=10, null=True)),
                ('sscidb', models.CharField(blank=True, max_length=10, null=True)),
                ('sspkk', models.CharField(blank=True, max_length=10, null=True)),
                ('ssssm', models.CharField(blank=True, max_length=10, null=True)),
                ('sskk', models.CharField(blank=True, max_length=10, null=True)),
                ('ssinsurance', models.CharField(blank=True, max_length=10, null=True)),
                ('ssgambar', models.CharField(blank=True, max_length=10, null=True)),
                ('ssmrksatulink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.mrksatu')),
                ('ssnosebutharga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.noperolehan')),
            ],
            options={
                'verbose_name_plural': 'Senarai Semakan',
            },
        ),
    ]
