# Generated by Django 3.2 on 2021-06-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0011_auto_20210515_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrksatu',
            name='mrksatutarikhjangkasiap',
            field=models.DateField(blank=True, null=True),
        ),
    ]
