# Generated by Django 3.1.2 on 2021-02-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0012_senaraisemakan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSMK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psmknojaminanbanka', models.CharField(blank=True, max_length=50, null=True)),
                ('psmkhargajaminana', models.CharField(blank=True, max_length=50, null=True)),
                ('psmkbakiwangjaminana', models.CharField(blank=True, max_length=50, null=True)),
                ('psmknojaminanbankab', models.CharField(blank=True, max_length=50, null=True)),
                ('psmkhargajaminanb', models.CharField(blank=True, max_length=50, null=True)),
                ('psmkbakiwangjaminanb', models.CharField(blank=True, max_length=50, null=True)),
                ('psmkkosbon', models.CharField(blank=True, max_length=50, null=True)),
                ('psmkbakikos', models.CharField(blank=True, max_length=50, null=True)),
                ('psmkpegawaipenguasa', models.CharField(blank=True, max_length=50, null=True)),
                ('psmkjawatan', models.CharField(blank=True, max_length=50, null=True)),
                ('psmkmrksatulink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.mrksatu')),
                ('psmknosebutharga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.noperolehan')),
            ],
            options={
                'verbose_name_plural': 'Perakuan Siap Membaiki Kecacatan',
            },
        ),
    ]
