# Generated by Django 3.2 on 2021-06-11 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0012_alter_mrksatu_mrksatutarikhjangkasiap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporansiapkerja',
            name='lskmrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bindtwo', to='jpskit.mrksatu'),
        ),
        migrations.AlterField(
            model_name='mrkdua',
            name='mrksatulink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bindone', to='jpskit.mrksatu'),
        ),
    ]
