# Generated by Django 3.1.2 on 2021-01-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0012_auto_20210124_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='isSungai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sg_cabang', models.CharField(blank=True, max_length=50, null=True)),
                ('sg_pangjang', models.CharField(blank=True, max_length=50, null=True)),
                ('sg_daerah', models.CharField(blank=True, max_length=50, null=True)),
                ('sg_noshet', models.CharField(blank=True, max_length=50, null=True)),
                ('sg_norujukan', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sistem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemname', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subsistem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsistemname', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
