# Generated by Django 3.2 on 2021-06-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0012_kosprojek_kosnosebut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kosprojek',
            name='kosnosebut',
        ),
    ]
