# Generated by Django 3.1.2 on 2021-01-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0013_issungai_sistem_subsistem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsistem',
            name='sistemlink',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jpskit.sistem'),
            preserve_default=False,
        ),
    ]
