# Generated by Django 3.1.2 on 2021-01-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0013_projek_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRK2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MRK1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noinden', models.CharField(blank=True, max_length=50, null=True)),
                ('gred', models.CharField(blank=True, max_length=20, null=True)),
                ('kategori', models.CharField(blank=True, max_length=20, null=True)),
                ('pengkhususan', models.CharField(blank=True, max_length=100, null=True)),
                ('tarikhmula', models.CharField(blank=True, max_length=50, null=True)),
                ('tarikhjangkasiap', models.CharField(blank=True, max_length=50, null=True)),
                ('pegawai', models.CharField(blank=True, max_length=100, null=True)),
                ('jawatan', models.CharField(blank=True, max_length=50, null=True)),
                ('kosprojek', models.CharField(blank=True, max_length=100, null=True)),
                ('tarikhdaftar', models.CharField(blank=True, max_length=50, null=True)),
                ('nosebutharga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jpskit.noperolehan')),
            ],
        ),
    ]
