# Generated by Django 3.1.2 on 2021-02-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0013_psmk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratPJaminanbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rujukanbank', models.CharField(blank=True, max_length=50, null=True)),
                ('namabank', models.CharField(blank=True, max_length=50, null=True)),
                ('alamatbank', models.CharField(blank=True, max_length=200, null=True)),
                ('alamatpemborongsurat', models.CharField(blank=True, max_length=200, null=True)),
                ('jbankknosebutharga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.noperolehan')),
                ('jbankmrksatulink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.mrksatu')),
            ],
            options={
                'verbose_name_plural': 'Surat Pelepasan Jaminan Bank',
            },
        ),
        migrations.CreateModel(
            name='Perakuanpwjp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rujukantuan', models.CharField(blank=True, max_length=50, null=True)),
                ('rujukankami', models.CharField(blank=True, max_length=50, null=True)),
                ('namarujukan', models.CharField(blank=True, max_length=150, null=True)),
                ('alamatrujukan', models.CharField(blank=True, max_length=200, null=True)),
                ('koswjp', models.CharField(blank=True, max_length=50, null=True)),
                ('wjppegawai', models.CharField(blank=True, max_length=50, null=True)),
                ('wjpjawatan', models.CharField(blank=True, max_length=50, null=True)),
                ('wjpknosebutharga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.noperolehan')),
                ('wjpmrksatulink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jpskit.mrksatu')),
            ],
            options={
                'verbose_name_plural': 'PPWJP',
            },
        ),
    ]
