# Generated by Django 3.1.2 on 2021-01-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpskit', '0014_mrk1_mrk2'),
    ]

    operations = [
        migrations.AddField(
            model_name='projek',
            name='nosebuthargalink',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jpskit.noperolehan'),
            preserve_default=False,
        ),
    ]
