# Generated by Django 3.1.2 on 2021-01-13 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jpskit', '0015_projek_nosebuthargalink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projek',
            old_name='tarikh',
            new_name='daerah',
        ),
        migrations.RenameField(
            model_name='projek',
            old_name='title',
            new_name='tajukkerja',
        ),
        migrations.RemoveField(
            model_name='projek',
            name='vendor',
        ),
        migrations.AddField(
            model_name='projek',
            name='pegawaiselia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
