# Generated by Django 3.1.2 on 2021-01-13 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jpskit', '0016_auto_20210113_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noperolehan',
            name='pegawaiselia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
